"""add_role_submission_payout_pipeline

Revision ID: d9ceb9d1df2a
Revises: e96f05a8cae1
Create Date: 2026-05-23 20:15:28.192414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ceb9d1df2a'
down_revision: Union[str, None] = 'e96f05a8cae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_id'), 'auditlog', ['id'], unique=False)
    op.create_table('payoutaccount',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number_encrypted', sa.String(), nullable=False),
    sa.Column('account_number_masked', sa.String(), nullable=False),
    sa.Column('account_holder', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payoutaccount_id'), 'payoutaccount', ['id'], unique=False)
    op.create_table('videosubmission',
    sa.Column('submission_no', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('original_storage_key', sa.String(), nullable=True),
    sa.Column('processed_storage_key', sa.String(), nullable=True),
    sa.Column('thumbnail_storage_key', sa.String(), nullable=True),
    sa.Column('original_file_hash', sa.String(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('region_sido', sa.String(), nullable=False),
    sa.Column('region_sigungu', sa.String(), nullable=True),
    sa.Column('approximate_address', sa.String(), nullable=True),
    sa.Column('original_lat', sa.Float(), nullable=True),
    sa.Column('original_lng', sa.Float(), nullable=True),
    sa.Column('noisy_lat', sa.Float(), nullable=True),
    sa.Column('noisy_lng', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'NEEDS_MORE_INFO', 'APPROVED', 'REJECTED', 'DUPLICATE', 'RIGHTS_RISK', 'PROCESSING_PRIVACY', 'READY_TO_PUBLISH', 'PUBLISHED', 'ARCHIVED', name='submissionstatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('review_memo', sa.Text(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videosubmission_id'), 'videosubmission', ['id'], unique=False)
    op.create_index(op.f('ix_videosubmission_submission_no'), 'videosubmission', ['submission_no'], unique=True)
    op.create_table('adminreview',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'NEEDS_MORE_INFO', 'DUPLICATE', 'RIGHTS_RISK', name='reviewdecision'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('checklist_playable', sa.Boolean(), nullable=True),
    sa.Column('checklist_under_one_minute', sa.Boolean(), nullable=True),
    sa.Column('checklist_likely_original', sa.Boolean(), nullable=True),
    sa.Column('checklist_no_news_source', sa.Boolean(), nullable=True),
    sa.Column('checklist_blur_possible', sa.Boolean(), nullable=True),
    sa.Column('checklist_location_safe', sa.Boolean(), nullable=True),
    sa.Column('checklist_not_sensitive', sa.Boolean(), nullable=True),
    sa.Column('checklist_payout_eligible', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['videosubmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminreview_id'), 'adminreview', ['id'], unique=False)
    op.create_table('contentagreement',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agreement_version', sa.String(), nullable=False),
    sa.Column('is_original_owner', sa.Boolean(), nullable=False),
    sa.Column('is_rights_holder', sa.Boolean(), nullable=False),
    sa.Column('commercial_use_agreed', sa.Boolean(), nullable=False),
    sa.Column('edit_and_blur_agreed', sa.Boolean(), nullable=False),
    sa.Column('warranty_agreed', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_agreed', sa.Boolean(), nullable=False),
    sa.Column('reward_policy_confirmed', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('file_hash_at_agreement', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['videosubmission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_contentagreement_id'), 'contentagreement', ['id'], unique=False)
    op.create_table('payout',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payout_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NOT_ELIGIBLE', 'PAYOUT_PENDING', 'PAYOUT_PROCESSING', 'PAID', 'PAYOUT_FAILED', 'PAYOUT_HOLD', 'CANCELLED', name='payoutstatus'), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paid_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payout_account_id'], ['payoutaccount.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['videosubmission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_payout_id'), 'payout', ['id'], unique=False)
    op.alter_column('casestatus', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('user', sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.alter_column('casestatus', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_payout_id'), table_name='payout')
    op.drop_table('payout')
    op.drop_index(op.f('ix_contentagreement_id'), table_name='contentagreement')
    op.drop_table('contentagreement')
    op.drop_index(op.f('ix_adminreview_id'), table_name='adminreview')
    op.drop_table('adminreview')
    op.drop_index(op.f('ix_videosubmission_submission_no'), table_name='videosubmission')
    op.drop_index(op.f('ix_videosubmission_id'), table_name='videosubmission')
    op.drop_table('videosubmission')
    op.drop_index(op.f('ix_payoutaccount_id'), table_name='payoutaccount')
    op.drop_table('payoutaccount')
    op.drop_index(op.f('ix_auditlog_id'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
